Repository JBaczuk/bscript-parser, pull requests merged in 2019-03, with the labels that each got.

#44 Add TravisCI support. Implements #42
  .gitignore
  .travis.yml
  README.md
Labels: tooling

#52 add CLI. resolves #45
  README.md
  bin/bscript.js
  package-lock.json
  package.json
Labels: enhancement

#54 Fix bug in word<=>opcode conversion. Fixes #53
  src/opcodes.js
  test/opcodesTests.js
Labels: bug

#59 Options validation. Resolves #58
  index.js
  package-lock.json
  src/bscript.js
  src/options.js
  test/parseTests.js
Labels: enhancement

#60 Improved descriptions for pushdata opcodes. Resolves #56
  src/opcodes.js
  test/opcodesTests.js
Labels: enhancement

#61 Opcode functions accept numeric string. Resolves #51
  src/opcodes.js
  test/opcodesTests.js
Labels: enhancement

#64 Template placeholders are parsed with an end index. Fixes #63
  src/parseAsm.js
Labels: bug
